// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Corrected_typo_in_TemplateRow_ReferenceOverride_column_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corrected_typo_in_TemplateRow_ReferenceOverride_column_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202110251354383_Corrected_typo_in_TemplateRow_ReferenceOverride_column_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
