// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Increased_length_of_PspReference_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Increased_length_of_PspReference_field));
        
        string IMigrationMetadata.Id
        {
            get { return "202201261102016_Increased_length_of_PspReference_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
