// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Made_AccountHolder_SurnameSoundex_a_computed_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Made_AccountHolder_SurnameSoundex_a_computed_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202207261339251_Made_AccountHolder_SurnameSoundex_a_computed_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
