// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_new_account_reference_validation_entities_and_removed_old_ones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_new_account_reference_validation_entities_and_removed_old_ones));
        
        string IMigrationMetadata.Id
        {
            get { return "202204041823127_Added_new_account_reference_validation_entities_and_removed_old_ones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
