// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update_FundMessageMetadata_to_use_MetadataKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_FundMessageMetadata_to_use_MetadataKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "202210040915558_Update_FundMessageMetadata_to_use_MetadataKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
